# -*- coding: utf-8 -*-
"""Assignment_1_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19OOoXGLOBaS9EorSEduR27g2Lk4cOBNN
"""

!pip install --upgrade wandb
import wandb
!wandb login 7c2b51b201fca423d3798d6c77c45bc79501464a

!pip install --upgrade wandb
import wandb
!wandb login 7c2b51b201fca423d3798d6c77c45bc79501464a

from wandb.keras import WandbCallback
from keras.datasets import fashion_mnist
from matplotlib import pyplot as plt
(train_X,train_Y),(test_X,test_Y)=fashion_mnist.load_data()

wandb.init(project='Fashion-MNIST-Images',entity='kumar-vaibhav')
class_names=['T-shirt/top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle boot']
images=[]
labels=[]
count=0
for i in range(len(train_Y)):
  if train_Y[i]==count:
    images.append(train_X[i])
    labels.append(class_names[train_Y[i]])
    count=count+1
  else:
    pass
  if count==10:
    break
  
wandb.log({"Question 1": [wandb.Image(img, caption=lbl) for img,lbl in zip(images,labels)]})